<a href="https://colab.research.google.com/github/YeniferG/Yenifer_Guaje_KC/blob/master/TALLER_DATA_SCIENCE_SEMANA_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
import time

**<h1 align="center">TALLER 1 DATA SCIENCE</h1>**


**1.**	Tienen el siguiente arreglo : 

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Como es posible obtener el siguiente resultado:

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])


***ALTERNATIVA 1***

In [ ]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)
print("----------------------------------")
a = np.delete(arr,(1,3,5,7,9))
ind=[1,2,3,4,5]
print(np.insert(a,(ind),-1))

[0 1 2 3 4 5 6 7 8 9]
----------------------------------
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


***ALTERNATIVA 2***

In [ ]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)
print("-------------------------------")
indices = [1,3,5,7,9]
arr.put(indices,-1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
-------------------------------
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


***ALTERNATIVA 3***

In [ ]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)
print("----------------------------------")
ind=[1,3,5,7,9]
arr[ind]=-1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
----------------------------------
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**2.**	Tienen el siguiente input:

np.arange(10)

Como se puede hacer para obtener el siguiente resultado:

###> array([[0, 1, 2, 3, 4],
###>        [5, 6, 7, 8, 9]])


In [ ]:
a=np.arange(10)
print(a)
print(a.shape)
print("-------------")
a=a.reshape((2,5))
print(a)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
-------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


**3.**	Con base en el siguiente input:

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Obtener el siguiente resultado
###> array([[0, 1, 2, 3, 4],
###>        [5, 6, 7, 8, 9],
###>        [1, 1, 1, 1, 1],
###>        [1, 1, 1, 1, 1]])


In [ ]:
a = np.arange(10).reshape(2,-1)
print(a)
print("--------------------")
b = np.repeat(1,10).reshape(2,-1)
print(b)
print("--------------------")
print(np.concatenate((a,b),axis=0))

[[0 1 2 3 4]
 [5 6 7 8 9]]
--------------------
[[1 1 1 1 1]
 [1 1 1 1 1]]
--------------------
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


**4.**	Con base en el siguiente input:

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

Obtener el siguiente output

array([2, 4])


***ALTERNATIVA 1***

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
print(a)
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(b)
print("---------------")
array=([a[1],b[5]])
print(array)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
---------------
[2, 4]


***ALTERNATIVA 2***

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
print(a)
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(b)
print("---------------")
print(np.intersect1d(a,b))

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
---------------
[2 4]


**5.**	Del siguiente input:

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

Obtener el siguiente output

array([1,2,3,4])


In [ ]:
a = np.array([1,2,3,4,5])
print(a)
b = np.array([5,6,7,8,9])
print(b)
print("------------------")
c = np.concatenate((a,b))
print(c[0:4])

[1 2 3 4 5]
[5 6 7 8 9]
------------------
[1 2 3 4]


**6.** Con el siguiente input:

a = np.array([2, 6, 1, 9, 10, 3, 27])

Obtener:

(array([6, 9, 10]),)


***ALTERNATIVA 1***

In [7]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a)
print("-------------------------------")
print(a[[1,3,4]])

[ 2  6  1  9 10  3 27]
-------------------------------
[ 6  9 10]


***ALTERNATIVA 2***

In [6]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a)
print("-------------------------------")
indices=[1,3,4]
print(a[indices])

[ 2  6  1  9 10  3 27]
-------------------------------
[ 6  9 10]


**7.**	Invertir las filas de un arreglo de matriz 2D

arr = np.arange(9).reshape(3,3)

Output deseado:

###> array([[6, 7, 8],
###>       [3, 4, 5],
###>       [0, 1, 2]])


In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)
print("---------------------------------")
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
---------------------------------


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])